name: Publish to NPM

on:
  push:
    branches:
      - main # Puedes cambiar esto a la rama que prefieras

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20] # Lista de versiones de Node.js que quieres probar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install # Instala todas las dependencias listadas en package.json

      - name: Increment version
        run: npm version patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: matrix.node-version == '18' # Solo publica desde una versión específica de Node.js
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
